version: '3'

networks:
    laravel_dockerize:

services:
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        container_name: "${PROJECT_NAME}_nginx"
        working_dir: /var/www/html
        ports:
            - "80:80"
        volumes:
            - ../:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_dockerize
        depends_on:
            - mysql
            - php

    mysql:
        image: mysql:8
        restart: unless-stopped
        container_name: "${PROJECT_NAME}_mysql"
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./mysql/data:/var/lib/mysql
        networks:
            - laravel_dockerize

    php:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: "${PROJECT_NAME}_php"
        volumes:
            - ../:/var/www/html
            - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        ports:
            - "9000:9000"
        networks:
            - laravel_dockerize

